/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "grxcanjeqpejwxdxdfen"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyeGNhbmplcXBland4ZHhkZmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1MzMyNjYsImV4cCI6MjA4NjEwOTI2Nn0.otZ1798_3gv8sZk--atyuZg-rX2qMsyuT8tTz8GX0tE"